# YOLO
YOLO_MODEL = r"B:\UAV Evasion\UAVEvasionSystem\yolov8s_trained.pt"
DRONE_CLASSES = [0]
CONFIDENCE = 0.4
IOU_THRESHOLD = 0.3

CLASS_NAMES = {
    0 : 'drone'
}

# DEEPSORT
MAX_AGE = 30
N_INIT = 3
MAX_IOU_DISTANCE = 0.7
MAX_COSINE_DISTANCE = 0.2

# UAV
UAV_SPEED = 5
COMMAND_THRESHOLD = 50

# Visual
SHOW_TRAILS = True
TRAIL_LENGTH = 30
SHOW_VELOCITY = True
GUIDANCE_ENABLED = True